scrapper:
  scheduler:
    interval: "10s"
  update-link-interval: "11s"

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

client:
  github-api: "https://api.github.com"
  stackoverflow-api: "https://api.stackexchange.com/2.2"

spring:
  liquibase:
    enabled: false
