bot:
  name: "ItSubscriberBot"
  token: ${BOT_TOKEN}
  updates:
    fixed-delay: "1s"
  rabbitMQ:
    exchange: links.exchange
    queue: link.queue
    routingKey: update-link

server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5673
    username: rmuser
    password: rmpassword

management:
  server:
    port: 8083
  endpoints:
    enabled-by-default: true
    web:
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
      exposure:
        include: [ "info", "health", "prometheus" ]
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
