name: bot

on:
  push:
    paths:
      - 'bot/**'
  pull_request:
    paths:
      - 'bot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven package
        run: mvn package -pl bot -am

      - name: Build and push Docker image
          env:
            DOCKER_USERNAME: ${{ secrets.USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.PASSWORD }}
            IMAGE_NAME: ghcr.io/Alexander-1703/bot:latest
          run: |
            docker build /bot -t $IMAGE_NAME
            echo $PASSWORD | docker login ghcr.io -u $USERNAME --password-stdin
            docker push $IMAGE_NAME

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Static code analysis
        run: mvn -pl bot -am checkstyle:check

