name: scrapper

on:
  push:
    paths:
      - 'scrapper/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Add environment variable to application.yaml
        run: |
          sed -i "s/\${GITHUB_TOKEN}/$GITHUB_TOKEN/g" ./scrapper/src/main/resources/application.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.SCRAPPER_GITHUB_TOKEN }}

      - name: Build scrapper-jooq
        run: mvn package -pl scrapper-jooq -am

      - name: Generate jooq files in scrapper
        run: java -jar scrapper-jooq/target/scrapper-jooq-1.0-SNAPSHOT.jar

      - name: Maven package
        run: mvn package -pl scrapper -am

      - name: Build and push Docker image
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          IMAGE_NAME: ghcr.io/alexander-1703/scrapper:latest
        run: |
          docker build ./scrapper -t $IMAGE_NAME
          echo $PASSWORD | docker login ghcr.io -u $USERNAME --password-stdin
          docker push $IMAGE_NAME

  checkstyle:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Static code analysis
        run: mvn -pl scrapper -am checkstyle:check -Dcheckstyle.config.location=checkstyle.xml

